### ISSUE TITLE
Dynamically choose folder delimiters

### ISSUE THREAD

**Issue by tweinreich** [jfarley248/iTunes_Backup_Reader#2]
When I ran your script on Linux I noticed that you often use `replace('/', '\\')` to fix the paths for Windows (_including some other occurrences when you concatenate_). To get it working for every OS you could detect the OS (e.g. by using `os.name`) and then decide what the delimiter should be. 

**Edit:**
I just replaced all static `"\\"` with a `"/"` and commented out all replaces like the one mentioned and what can I say? It works! :-D

I'm really glad because I tried a few different tools without any success though I got them to run (_after some time I needed to get there_). Thanks a lot!

P.S.: Here are my temporary changes: [Fork of your repo](https://github.com/tweinreich/iTunes_Backup_Reader/commit/defabf6a14d05a4cb858a10d1dc4c8bd61a89fa2)

**Comment by andrewdotn** [comment]
[`os.path.join()`](https://docs.python.org/3/library/os.path.html#os.path.join) might be even better , as in

    >>> os.path.join('foo', 'bar', 'baz')
    'foo/bar/baz'

on mac/linux, and

    >>> os.path.join('foo', 'bar', 'baz')
    'foo\\bar\\baz'

on windows.

**Comment by tweinreich** [comment]
Hey @andrewdotn thank you for pointing that out - Yes that's even better.

**Comment by jfarley248** [comment]
Thank you @andrewdotn @tweinreich for helping with this! Just updated to hopefully resolve this issue
