### ISSUE TITLE
Can not read data if no Status.plist file is present

### ISSUE THREAD

**Issue by ghost** [jfarley248/iTunes_Backup_Reader#5]
I have an incomplete backup that contains the "info.plist", "Manifest.mbdb", and "Manifest.plist" files, as well as the other long name files. It does not contain a "Status.plist" file. Other tools are able to pull data from it (In the trial), but this reader fails without the "Status.plist" file. Can you add a flag that allows the program to continue with the information it has?

**Comment by jfarley248** [comment]
That's great idea. Will implement

**Comment by jfarley248** [comment]
Fixed with latest commit
